# Generated by Django 5.0.1 on 2024-01-28 21:49

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('primary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('secondary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('force', models.CharField(blank=True, choices=[('pull', 'Pull'), ('push', 'Push'), ('static', 'Static')], max_length=50, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=50)),
                ('mechanic', models.CharField(blank=True, choices=[('compound', 'Compound'), ('isolation', 'Isolation')], max_length=50, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('body only', 'Body Only'), ('machine', 'Machine'), ('other', 'Other'), ('foam roll', 'Foam Roll'), ('kettlebells', 'Kettlebells'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('barbell', 'Barbell'), ('bands', 'Bands'), ('medicine ball', 'Medicine Ball'), ('exercise ball', 'Exercise Ball'), ('e-z curl bar', 'E-Z Curl Bar')], max_length=50, null=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('stretching', 'Stretching'), ('plyometrics', 'Plyometrics'), ('strongman', 'Strongman'), ('powerlifting', 'Powerlifting'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting')], max_length=50)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('tips', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
    ]
